import {
  checkPattern,
  type CcMove,
  type CcPlayerView,
  type PlayerSeat,
  type RoomSnapshot,
} from '@rivalrush/shared';
import { useEffect, useRef, useState } from 'react';
import { ResultSheet } from '../../components/game/ResultSheet';
import { TimerRing } from '../../components/game/TimerRing';
import { TopBar } from '../../components/game/TopBar';
import { useShake } from '../../components/game/useShake';
import { Button, Pill, Screen } from '../../components/ui';
import { remainingMs, useNow } from '../../lib/clock';
import { haptic } from '../../lib/telegram';
import { useRoom } from '../../store/room';
import { useSession } from '../../store/session';
import { toast } from '../../store/toasts';
import { FeedbackPips, Palette, PatternRow } from './pieces';

/** Color Cipher's colors: the "my turn" banner uses its own gradient, distinct from Crack the Code. */
const MY_TURN = 'bg-gradient-to-r from-[#0b7c86] to-[#6b3fd1] text-white';

export function ColorCipherGame({ room }: { room: RoomSnapshot }) {
  const me = useSession((s) => s.user!.id);
  const view = room.game!.view;
  if (view.gameId !== 'color-cipher') return null;
  const opponent = room.players.find((p) => p.userId !== me) ?? null;
  const over = view.phase === 'FINISHED' || view.phase === 'ABANDONED';
  const len = view.settings.patternLength;
  const secret = (pattern: string | null) => (
    <PatternRow value={pattern ?? ''} length={len} size="sm" />
  );

  return (
    <Screen className="gap-3">
      <TopBar
        room={room}
        opponent={opponent}
        over={over}
        detail={`${len} tiles · ${view.settings.colorCount} colors`}
      />
      {view.phase === 'SETUP' ? (
        <PatternSetup view={view} opponent={opponent} />
      ) : (
        <Board view={view} opponent={opponent} over={over} />
      )}
      {over && view.result && (
        <ResultSheet
          room={room}
          result={view.result}
          me={me}
          opponent={opponent}
          secretLabel="pattern"
          mySecret={secret(view.mySecret)}
          theirSecret={secret(view.opponentSecret)}
        />
      )}
    </Screen>
  );
}

function PatternSetup({ view, opponent }: { view: CcPlayerView; opponent: PlayerSeat | null }) {
  const offset = useRoom((s) => s.offset);
  const now = useNow();
  const [pattern, setPattern] = useState('');
  const [busy, setBusy] = useState(false);
  const [shake, doShake] = useShake();
  const len = view.settings.patternLength;
  const left = remainingMs(view.setupDeadlineAt, offset, now);
  const oppReady = view.players.find((p) => p.userId !== view.me)?.hasSecret ?? false;

  const lock = async () => {
    if (checkPattern(pattern, len, view.settings.colorCount) !== 'ok') {
      doShake();
      haptic.error();
      return;
    }
    setBusy(true);
    const err = await useRoom.getState().act({ type: 'SET_SECRET', pattern });
    setBusy(false);
    if (err) {
      doShake();
      haptic.error();
      toast(err.message, 'bad');
    } else haptic.success();
  };

  return (
    <div className="flex flex-1 flex-col gap-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-black">Hide your pattern</h1>
          <p className="text-sm text-muted">
            {len} tiles, colors can repeat. Your rival will try to crack it.
          </p>
        </div>
        <TimerRing remainingMs={left} totalMs={60_000} urgent={(left ?? 99_999) < 10_000} />
      </div>

      {view.mySecret ? (
        <div
          className="flex flex-1 flex-col items-center justify-center gap-4 text-center"
          data-testid="secret-locked"
        >
          <PatternRow value={view.mySecret} length={len} size="lg" />
          <Pill tone="good">
            🔒 Pattern locked{view.mySecretAutoGenerated ? ' (picked for you)' : ''}
          </Pill>
          <p className="text-muted">
            {oppReady
              ? 'Starting…'
              : `Waiting for ${opponent?.displayName ?? 'your rival'} to lock in…`}
          </p>
        </div>
      ) : (
        <>
          <div className="py-4">
            <PatternRow value={pattern} length={len} size="lg" shake={shake} />
          </div>
          <p className="text-center text-sm text-muted">
            {oppReady ? `${opponent?.displayName ?? 'Your rival'} is locked in ✓` : ' '}
          </p>
          <div className="mt-auto flex flex-col gap-3">
            <Palette value={pattern} length={len} onChange={setPattern} disabled={busy} />
            <Button
              onClick={lock}
              disabled={busy || pattern.length !== len}
              data-testid="lock-secret"
            >
              Lock it in
            </Button>
          </div>
        </>
      )}
    </div>
  );
}

function MoveRow({ m, len, mine }: { m: CcMove; len: number; mine: boolean }) {
  return (
    <li
      className="flex animate-rise items-center gap-3 rounded-2xl bg-card px-3 py-2"
      data-testid={mine ? 'my-move' : 'their-move'}
    >
      <span className="w-6 text-xs font-bold text-muted tabular-nums">{m.turnNumber}</span>
      {m.timedOut || m.guess === null ? (
        <span className="flex-1 text-sm font-bold text-muted">⏱ Timed out</span>
      ) : (
        <div className="flex-1">
          <PatternRow value={m.guess} length={len} size="sm" testId="move-pattern" />
        </div>
      )}
      {!m.timedOut && (
        <>
          <FeedbackPips exact={m.exact} partial={m.partial} length={len} />
          <span className="w-16 text-right text-xs font-bold tabular-nums">
            <span className="text-bull">{m.exact} exact</span>
            <br />
            <span className="text-cow">{m.partial} close</span>
          </span>
        </>
      )}
    </li>
  );
}

function Board({
  view,
  opponent,
  over,
}: {
  view: CcPlayerView;
  opponent: PlayerSeat | null;
  over: boolean;
}) {
  const offset = useRoom((s) => s.offset);
  const now = useNow();
  const [tab, setTab] = useState<'mine' | 'theirs'>('mine');
  const len = view.settings.patternLength;
  const myTurn = !over && view.currentTurn === view.me;
  const meP = view.players.find((p) => p.userId === view.me)!;
  const oppP = view.players.find((p) => p.userId !== view.me)!;
  const left = remainingMs(view.turnDeadlineAt, offset, now);
  const myMoves = view.moves.filter((m) => m.playerId === view.me);
  const theirMoves = view.moves.filter((m) => m.playerId !== view.me);
  const lastTurn = useRef(view.currentTurn);

  useEffect(() => {
    if (view.currentTurn === view.me && lastTurn.current !== view.me) haptic.press();
    lastTurn.current = view.currentTurn;
  }, [view.currentTurn, view.me]);

  const turnText =
    view.phase === 'LAST_CHANCE'
      ? myTurn
        ? 'Last chance — crack it to tie!'
        : `${opponent?.displayName ?? 'Rival'}'s last chance`
      : myTurn
        ? 'Your turn'
        : `${opponent?.displayName ?? 'Rival'}'s turn`;

  return (
    <div className="flex flex-1 flex-col gap-3">
      {!over && (
        <div
          className={`flex items-center justify-between rounded-3xl px-4 py-3 ${myTurn ? MY_TURN : 'bg-card'} ${view.phase === 'LAST_CHANCE' ? 'ring-4 ring-cow' : ''}`}
          data-testid="turn-banner"
        >
          <div>
            <p className="text-xl font-black">{turnText}</p>
            <p className="text-xs opacity-80">
              You: {meP.guessesLeft} left · Them: {oppP.guessesLeft} left
            </p>
          </div>
          <TimerRing
            remainingMs={left}
            totalMs={view.settings.turnSeconds * 1000}
            urgent={(left ?? 99_999) < 10_000}
          />
        </div>
      )}

      <div className="flex items-center justify-between rounded-2xl bg-surface px-4 py-2">
        <span className="text-xs font-bold uppercase tracking-wider text-muted">Your pattern</span>
        <PatternRow value={view.mySecret ?? ''} length={len} size="sm" testId="my-secret" />
      </div>

      <div className="grid grid-cols-2 gap-1 rounded-2xl bg-surface p-1 text-sm font-bold">
        {(['mine', 'theirs'] as const).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={`h-9 rounded-xl ${tab === t ? 'bg-card text-text shadow' : 'text-muted'}`}
          >
            {t === 'mine'
              ? `Your guesses (${myMoves.length})`
              : `Their guesses (${theirMoves.length})`}
          </button>
        ))}
      </div>

      <ul className="flex min-h-24 flex-1 flex-col gap-2 overflow-y-auto">
        {(tab === 'mine' ? myMoves : theirMoves)
          .slice()
          .reverse()
          .map((m) => (
            <MoveRow key={`${m.playerId}-${m.turnNumber}`} m={m} len={len} mine={tab === 'mine'} />
          ))}
        {(tab === 'mine' ? myMoves : theirMoves).length === 0 && (
          <li className="py-6 text-center text-sm text-muted">
            {tab === 'mine' ? (
              <>
                No guesses yet. <span className="font-bold text-bull">◆ Exact</span> = right color,
                right spot. <span className="font-bold text-cow">◇ Close</span> = right color, wrong
                spot.
              </>
            ) : (
              'They have not guessed yet.'
            )}
          </li>
        )}
      </ul>

      {!over &&
        (myTurn ? (
          // Keyed by move count so the input resets for every new turn.
          <GuessPanel key={view.moves.length} view={view} onGuessed={() => setTab('mine')} />
        ) : (
          <div className="rounded-3xl bg-card p-4 text-center" data-testid="waiting-turn">
            <p className="font-bold">{opponent?.displayName ?? 'Your rival'} is thinking…</p>
            <p className="text-sm text-muted">Their guesses are scored against your pattern.</p>
          </div>
        ))}
    </div>
  );
}

function GuessPanel({ view, onGuessed }: { view: CcPlayerView; onGuessed: () => void }) {
  const [guess, setGuess] = useState('');
  const [busy, setBusy] = useState(false);
  const [shake, doShake] = useShake();
  const len = view.settings.patternLength;
  const tried = view.moves.filter((m) => m.playerId === view.me);

  const submit = async () => {
    const check = checkPattern(guess, len, view.settings.colorCount);
    if (check !== 'ok' || tried.some((m) => m.guess === guess)) {
      doShake();
      haptic.error();
      if (check === 'ok') toast('You already tried that pattern', 'bad');
      return;
    }
    setBusy(true);
    const err = await useRoom.getState().act({ type: 'GUESS', pattern: guess });
    setBusy(false);
    if (err) {
      doShake();
      haptic.error();
      toast(err.message, 'bad');
      return;
    }
    onGuessed();
    const after = useRoom.getState().snapshot?.game?.view;
    const latest =
      after?.gameId === 'color-cipher'
        ? after.moves.filter((m) => m.playerId === view.me).at(-1)
        : undefined;
    if (latest && latest.exact + latest.partial > 0) haptic.success();
    else haptic.tap();
  };

  return (
    <div className="flex flex-col gap-3" data-testid="guess-panel">
      <PatternRow value={guess} length={len} size="lg" shake={shake} />
      <Palette value={guess} length={len} onChange={setGuess} disabled={busy} />
      <Button onClick={submit} disabled={busy || guess.length !== len} data-testid="submit-guess">
        Guess
      </Button>
    </div>
  );
}
