import { DEFAULT_CTC_SETTINGS, type CtcSettings } from '@rivalrush/shared';
import { describe, expect, it } from 'vitest';
import { crackTheCode as game, type CtcState } from '../../src/games/crack-the-code/game.js';
import type { Actor } from '../../src/games/engine/types.js';
import { seededRandom } from '../helpers/random.js';

const A = 'userA';
const B = 'userB';
const T0 = 1_000_000;

function create(settings: Partial<CtcSettings> = {}, firstPlayerIndex = 0): CtcState {
  return game.createInitialState(game.parseSettings({ ...settings }), {
    players: [A, B],
    firstPlayerIndex,
    now: T0,
    random: seededRandom(1),
  });
}

const p = (playerId: string): Actor => ({ kind: 'player', playerId });
const sys: Actor = { kind: 'system' };

function apply(state: CtcState, actor: Actor, action: unknown, now = T0 + 1000) {
  return game.applyAction(state, actor, action, { now, random: seededRandom(7) });
}

function must(state: CtcState, actor: Actor, action: unknown, now = T0 + 1000): CtcState {
  const r = apply(state, actor, action, now);
  if (!r.ok) throw new Error(`expected ok, got ${r.error.code}: ${r.error.message}`);
  return r.state;
}

function code(state: CtcState, actor: Actor, action: unknown, now = T0 + 1000): string {
  const r = apply(state, actor, action, now);
  if (r.ok) throw new Error('expected failure');
  return r.error.code;
}

/** A=1234, B=5678, A moves first, now playing. */
function playing(settings: Partial<CtcSettings> = {}): CtcState {
  let s = create(settings);
  const len = s.settings.codeLength;
  s = must(s, p(A), { type: 'SET_SECRET', code: '12345'.slice(0, len) });
  s = must(s, p(B), { type: 'SET_SECRET', code: '56789'.slice(0, len) });
  return s;
}

describe('setup', () => {
  it('starts in SETUP with a 60s deadline and no turn', () => {
    const s = create();
    expect(s.phase).toBe('SETUP');
    expect(s.setupDeadlineAt).toBe(T0 + 60_000);
    expect(s.currentTurn).toBeNull();
    expect(game.getNextDeadline(s)).toEqual({ at: T0 + 60_000, action: { type: '$TIMEOUT' } });
  });

  it('rejects invalid secrets with specific rules', () => {
    const s = create();
    expect(code(s, p(A), { type: 'SET_SECRET', code: '123' })).toBe('INVALID_SECRET');
    expect(code(s, p(A), { type: 'SET_SECRET', code: '1123' })).toBe('INVALID_SECRET');
    expect(code(s, p(A), { type: 'SET_SECRET', code: '12a4' })).toBe('INVALID_ACTION'); // fails schema
    expect(code(s, p(A), { type: 'SET_SECRET', code: '1234', extra: 1 })).toBe('INVALID_ACTION');
  });

  it('allows a leading zero', () => {
    const s = must(create(), p(A), { type: 'SET_SECRET', code: '0123' });
    expect(game.getPlayerView(s, A).mySecret).toBe('0123');
  });

  it('locks a secret once', () => {
    const s = must(create(), p(A), { type: 'SET_SECRET', code: '1234' });
    expect(code(s, p(A), { type: 'SET_SECRET', code: '5678' })).toBe('SECRET_ALREADY_SET');
  });

  it('moves to PLAYING with the first player on turn once both secrets are set', () => {
    const s = playing();
    expect(s.phase).toBe('PLAYING');
    expect(s.currentTurn).toBe(A);
    expect(s.turnDeadlineAt).toBe(T0 + 1000 + 45_000);
  });

  it('respects the chosen first player', () => {
    let s = create({}, 1);
    s = must(s, p(A), { type: 'SET_SECRET', code: '1234' });
    s = must(s, p(B), { type: 'SET_SECRET', code: '5678' });
    expect(s.currentTurn).toBe(B);
  });

  it('auto-generates missing secrets when the setup deadline passes', () => {
    let s = must(create(), p(A), { type: 'SET_SECRET', code: '1234' });
    expect(code(s, sys, { type: '$TIMEOUT' }, T0 + 59_999)).toBe('INVALID_ACTION');
    s = must(s, sys, { type: '$TIMEOUT' }, T0 + 60_000);
    expect(s.phase).toBe('PLAYING');
    const viewB = game.getPlayerView(s, B);
    expect(viewB.mySecret).toMatch(/^[0-9]{4}$/);
    expect(new Set(viewB.mySecret!).size).toBe(4);
    expect(viewB.mySecretAutoGenerated).toBe(true);
    expect(game.getPlayerView(s, A).mySecret).toBe('1234');
  });

  it('rejects a secret arriving exactly at the setup deadline (timer wins ties)', () => {
    const s = create();
    expect(code(s, p(A), { type: 'SET_SECRET', code: '1234' }, T0 + 60_000)).toBe('INVALID_ACTION');
  });

  it('rejects guesses during setup', () => {
    expect(code(create(), p(A), { type: 'GUESS', guess: '1234' })).toBe('GAME_NOT_STARTED');
  });
});

describe('turns', () => {
  it('enforces strict alternation', () => {
    let s = playing();
    expect(code(s, p(B), { type: 'GUESS', guess: '1234' })).toBe('NOT_YOUR_TURN');
    s = must(s, p(A), { type: 'GUESS', guess: '9012' });
    expect(s.currentTurn).toBe(B);
    expect(code(s, p(A), { type: 'GUESS', guess: '9013' })).toBe('NOT_YOUR_TURN');
    s = must(s, p(B), { type: 'GUESS', guess: '9012' });
    expect(s.currentTurn).toBe(A);
  });

  it('scores guesses against the opponent secret', () => {
    const s = must(playing(), p(A), { type: 'GUESS', guess: '5687' });
    expect(s.moves.at(-1)).toMatchObject({
      playerId: A,
      guess: '5687',
      bulls: 2,
      cows: 2,
      timedOut: false,
    });
  });

  it('rejects invalid and duplicate guesses without using the turn', () => {
    let s = playing();
    expect(code(s, p(A), { type: 'GUESS', guess: '1123' })).toBe('INVALID_GUESS');
    expect(code(s, p(A), { type: 'GUESS', guess: '123' })).toBe('INVALID_GUESS');
    s = must(s, p(A), { type: 'GUESS', guess: '9012' });
    s = must(s, p(B), { type: 'GUESS', guess: '9012' });
    expect(code(s, p(A), { type: 'GUESS', guess: '9012' })).toBe('DUPLICATE_GUESS');
    expect(s.players[0].turnsUsed).toBe(1);
  });

  it('rejects a guess arriving exactly at the turn deadline', () => {
    const s = playing();
    expect(code(s, p(A), { type: 'GUESS', guess: '9012' }, s.turnDeadlineAt!)).toBe(
      'NOT_YOUR_TURN',
    );
  });

  it('a turn timeout burns the turn and passes it', () => {
    let s = playing();
    expect(code(s, sys, { type: '$TIMEOUT' }, s.turnDeadlineAt! - 1)).toBe('INVALID_ACTION');
    s = must(s, sys, { type: '$TIMEOUT' }, s.turnDeadlineAt!);
    expect(s.currentTurn).toBe(B);
    expect(s.players[0].turnsUsed).toBe(1);
    expect(s.moves.at(-1)).toMatchObject({ playerId: A, guess: null, timedOut: true });
  });

  it('bumps the version on every accepted change only', () => {
    const s0 = playing();
    const v = s0.version;
    expect(apply(s0, p(B), { type: 'GUESS', guess: '1234' }).ok).toBe(false);
    const s1 = must(s0, p(A), { type: 'GUESS', guess: '9012' });
    expect(s1.version).toBe(v + 1);
    expect(s0.version).toBe(v); // immutability
  });
});

describe('endings', () => {
  it('second player cracking wins immediately (equal turns)', () => {
    let s = playing();
    s = must(s, p(A), { type: 'GUESS', guess: '9012' });
    s = must(s, p(B), { type: 'GUESS', guess: '1234' });
    expect(s.phase).toBe('FINISHED');
    expect(game.getResult(s)).toEqual({ outcome: 'win', winnerId: B, reason: 'cracked' });
  });

  it('equalizer: first player cracks → second gets one last chance and misses → first wins', () => {
    let s = must(playing(), p(A), { type: 'GUESS', guess: '5678' });
    expect(s.phase).toBe('LAST_CHANCE');
    expect(s.currentTurn).toBe(B);
    expect(code(s, p(A), { type: 'GUESS', guess: '9012' })).toBe('NOT_YOUR_TURN');
    s = must(s, p(B), { type: 'GUESS', guess: '9012' });
    expect(game.getResult(s)).toEqual({ outcome: 'win', winnerId: A, reason: 'cracked' });
  });

  it('equalizer: second player also cracks → draw', () => {
    let s = must(playing(), p(A), { type: 'GUESS', guess: '5678' });
    s = must(s, p(B), { type: 'GUESS', guess: '1234' });
    expect(game.getResult(s)).toEqual({ outcome: 'draw', winnerId: null, reason: 'both_cracked' });
  });

  it('equalizer: second player times out on the last chance → first wins', () => {
    let s = must(playing(), p(A), { type: 'GUESS', guess: '5678' });
    s = must(s, sys, { type: '$TIMEOUT' }, s.turnDeadlineAt!);
    expect(game.getResult(s)).toEqual({ outcome: 'win', winnerId: A, reason: 'cracked' });
  });

  it('both players out of guesses → draw, and nobody exceeds the limit', () => {
    let s = playing({ maxGuesses: 8 });
    const wrong = ['9012', '9013', '9014', '9015', '9016', '9017', '9018', '9023'];
    for (const g of wrong) {
      s = must(s, p(A), { type: 'GUESS', guess: g });
      if (s.phase !== 'PLAYING') break;
      s = must(s, p(B), { type: 'GUESS', guess: g });
    }
    expect(game.getResult(s)).toEqual({
      outcome: 'draw',
      winnerId: null,
      reason: 'out_of_guesses',
    });
    expect(s.players.map((x) => x.turnsUsed)).toEqual([8, 8]);
    expect(code(s, p(A), { type: 'GUESS', guess: '9024' })).toBe('GAME_FINISHED');
  });

  it('timeouts count toward the guess limit so idle games terminate', () => {
    let s = playing({ maxGuesses: 8 });
    for (let i = 0; i < 16; i++) s = must(s, sys, { type: '$TIMEOUT' }, s.turnDeadlineAt!);
    expect(game.getResult(s)?.reason).toBe('out_of_guesses');
  });

  it('forfeit = loss for the forfeiting player, from any live phase', () => {
    const fromSetup = must(create(), p(A), { type: 'FORFEIT' });
    expect(game.getResult(fromSetup)).toEqual({ outcome: 'win', winnerId: B, reason: 'forfeit' });
    const fromPlay = must(playing(), p(B), { type: 'FORFEIT' });
    expect(game.getResult(fromPlay)).toEqual({ outcome: 'win', winnerId: A, reason: 'forfeit' });
    expect(fromPlay.phase).toBe('FINISHED');
  });

  it('abandon (grace expired) ends in ABANDONED with the other player winning', () => {
    const s = must(playing(), sys, { type: '$ABANDON', playerId: A });
    expect(s.phase).toBe('ABANDONED');
    expect(game.getResult(s)).toEqual({ outcome: 'win', winnerId: B, reason: 'abandoned' });
    expect(game.getNextDeadline(s)).toBeNull();
  });

  it('rejects every action once finished', () => {
    const s = must(playing(), p(B), { type: 'FORFEIT' });
    expect(code(s, p(A), { type: 'FORFEIT' })).toBe('GAME_FINISHED');
    expect(code(s, sys, { type: '$TIMEOUT' }, T0 + 10_000_000)).toBe('GAME_FINISHED');
  });

  it('ignores actions from non-players and unknown action types', () => {
    const s = playing();
    expect(code(s, p('mallory'), { type: 'GUESS', guess: '5678' })).toBe('NOT_ROOM_MEMBER');
    expect(code(s, p(A), { type: 'WIN' })).toBe('INVALID_ACTION');
    expect(code(s, p(A), { type: 'GUESS', guess: '5678', bulls: 4 })).toBe('INVALID_ACTION');
    expect(code(s, sys, { type: '$FORFEIT', playerId: 'mallory' })).toBe('NOT_ROOM_MEMBER');
  });
});

describe('secret isolation', () => {
  function assertNoOpponentSecret(s: CtcState) {
    const over = s.phase === 'FINISHED' || s.phase === 'ABANDONED';
    for (const [viewer, other] of [
      [A, B],
      [B, A],
    ] as const) {
      const view = game.getPlayerView(s, viewer);
      const otherSecret = s.players.find((x) => x.id === other)!.secret;
      if (!over) {
        expect(view.opponentSecret).toBeNull();
        // Guesses are public and may coincide with a secret; check everything else.
        const withoutGuesses = { ...view, moves: view.moves.map((m) => ({ ...m, guess: null })) };
        if (otherSecret) expect(JSON.stringify(withoutGuesses)).not.toContain(`"${otherSecret}"`);
      } else {
        expect(view.opponentSecret).toBe(otherSecret);
      }
    }
    const pubView = game.getPublicView(s);
    const pub = JSON.stringify({
      ...pubView,
      moves: pubView.moves.map((m) => ({ ...m, guess: null })),
    });
    for (const x of s.players) if (x.secret) expect(pub).not.toContain(`"${x.secret}"`);
    expect(pub).not.toContain('secret"');
  }

  it('never exposes an opponent secret before the end, across random full games', () => {
    for (let seed = 1; seed <= 60; seed++) {
      const rnd = seededRandom(seed);
      const len = 3 + (seed % 3);
      let s = game.createInitialState(game.parseSettings({ codeLength: len, maxGuesses: 8 }), {
        players: [A, B],
        firstPlayerIndex: seed % 2,
        now: T0,
        random: rnd,
      });
      let now = T0;
      assertNoOpponentSecret(s);
      if (seed % 4 !== 0)
        s = must(s, p(A), { type: 'SET_SECRET', code: '98765'.slice(0, len) }, now + 1);
      now = s.setupDeadlineAt!;
      s = must(s, sys, { type: '$TIMEOUT' }, now);
      assertNoOpponentSecret(s);
      let guard = 0;
      while ((s.phase === 'PLAYING' || s.phase === 'LAST_CHANCE') && guard++ < 50) {
        now += 1000;
        const mover = s.currentTurn!;
        const roll = rnd();
        if (roll < 0.15) s = must(s, sys, { type: '$TIMEOUT' }, (now = s.turnDeadlineAt!));
        else if (roll < 0.17) s = must(s, p(mover), { type: 'FORFEIT' }, now);
        else {
          const tried = new Set(s.moves.filter((m) => m.playerId === mover).map((m) => m.guess));
          let guess: string;
          do {
            guess = Array.from({ length: len }, () => '0123456789'[Math.floor(rnd() * 10)]).join(
              '',
            );
          } while (new Set(guess).size !== len || tried.has(guess));
          s = must(s, p(mover), { type: 'GUESS', guess }, now);
        }
        assertNoOpponentSecret(s);
      }
      expect(game.getResult(s)).not.toBeNull();
      expect(s.players[0].turnsUsed).toBeLessThanOrEqual(8);
      expect(s.players[1].turnsUsed).toBeLessThanOrEqual(8);
    }
  });

  it('getMoves contains no secrets', () => {
    let s = playing();
    s = must(s, p(A), { type: 'GUESS', guess: '9012' });
    const json = JSON.stringify(game.getMoves(s));
    expect(json).not.toContain('5678');
    expect(json).not.toContain('1234');
  });
});

describe('settings', () => {
  it('defaults and ranges', () => {
    expect(game.parseSettings(undefined)).toEqual(DEFAULT_CTC_SETTINGS);
    expect(() => game.parseSettings({ codeLength: 2 })).toThrow();
    expect(() => game.parseSettings({ turnSeconds: 91 })).toThrow();
  });
});
