import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { aid, alice, bob, GRACE_MS } from '../helpers/manager.js';
import { guess, lobby, opponentSecretOf, playing } from '../helpers/scenarios.js';
import { duelView } from '../helpers/views.js';

/**
 * Timers are server deadlines (epoch ms) stored in the game state. setTimeout only wakes the
 * room; the decision is made under the room lock by comparing the stored deadline with the
 * server clock. Clients only ever receive the deadline and the server time.
 */

const T0 = new Date('2026-10-05T12:00:00Z').getTime();
const TURN_MS = 45_000;

beforeEach(() => {
  vi.useFakeTimers();
  vi.setSystemTime(T0);
});
afterEach(() => {
  vi.useRealTimers();
});

describe('turn timer', () => {
  it('a normal turn: deadline = turn start + turnSeconds, sent with the server clock', async () => {
    const ctx = await playing();
    const snap = await ctx.manager.getSnapshot(ctx.first.userId, ctx.roomId);
    expect(duelView(snap.game!.view).turnStartedAt).toBe(T0);
    expect(duelView(snap.game!.view).turnDeadlineAt).toBe(T0 + TURN_MS);
    expect(snap.serverTime).toBe(T0);
    // Nothing happens before the deadline.
    await vi.advanceTimersByTimeAsync(TURN_MS - 1);
    expect((await ctx.state(ctx.roomId)).moves).toHaveLength(0);
  });

  it('timeout → the turn is burned and the next player gets a full turn from that moment', async () => {
    const ctx = await playing();
    await vi.advanceTimersByTimeAsync(TURN_MS);
    const s = await ctx.state(ctx.roomId);
    expect(s.moves).toEqual([
      expect.objectContaining({ playerId: ctx.first.userId, timedOut: true, turnNumber: 1 }),
    ]);
    expect(s.players.find((p) => p.id === ctx.first.userId)!.turnsUsed).toBe(1);
    expect(s.currentTurn).toBe(ctx.second.userId);
    expect(s.turnStartedAt).toBe(T0 + TURN_MS);
    expect(s.turnDeadlineAt).toBe(T0 + 2 * TURN_MS);
    // And the next timeout passes the turn back.
    await vi.advanceTimersByTimeAsync(TURN_MS);
    expect((await ctx.state(ctx.roomId)).currentTurn).toBe(ctx.first.userId);
  });

  it('clients are told about a timeout without doing anything (pushed snapshot + event)', async () => {
    const ctx = await playing();
    const before = ctx.changes.length;
    await vi.advanceTimersByTimeAsync(TURN_MS);
    const pushed = ctx.changes.slice(before);
    expect(pushed).toHaveLength(1);
    expect(pushed[0]!.events.map((e) => e.type)).toEqual(['turn_timed_out']);
  });

  it('a guess answers before the deadline cancels that deadline (no stray timeout later)', async () => {
    const ctx = await playing();
    await vi.advanceTimersByTimeAsync(TURN_MS - 5_000);
    await guess(ctx, ctx.first, '9012');
    const s = await ctx.state(ctx.roomId);
    expect(s.turnDeadlineAt).toBe(T0 + TURN_MS - 5_000 + TURN_MS);
    await vi.advanceTimersByTimeAsync(5_000); // the old deadline passes
    expect((await ctx.state(ctx.roomId)).moves.filter((m) => m.timedOut)).toHaveLength(0);
  });

  it('a late wake-up (event loop stalled past the deadline) applies exactly one timeout', async () => {
    const ctx = await playing();
    // The process was busy: the clock is far past the deadline when the room is next touched.
    vi.setSystemTime(T0 + 3 * TURN_MS + 10_000);
    const read = await ctx.manager.getSnapshot(ctx.second.userId, ctx.roomId);
    expect(duelView(read.game!.view).moves).toHaveLength(0); // reads never change state
    // The next mutation (here: a presence update) applies what is due first.
    await ctx.manager.connect(ctx.second.userId, ctx.roomId);
    const s = await ctx.state(ctx.roomId);
    expect(s.moves).toHaveLength(1);
    expect(s.turnDeadlineAt).toBe(T0 + 3 * TURN_MS + 10_000 + TURN_MS);
  });

  it('a client cannot move or extend the timer: there is no such action', async () => {
    const ctx = await playing();
    const v = (await ctx.state(ctx.roomId)).version;
    for (const action of [
      { type: '$TIMEOUT' },
      { type: 'SET_DEADLINE', at: T0 + 10 * TURN_MS },
      { type: 'GUESS', guess: '9012', turnDeadlineAt: T0 + 10 * TURN_MS },
    ]) {
      await ctx.manager
        .gameAction(ctx.first.userId, {
          roomId: ctx.roomId,
          actionId: aid(),
          clientVersion: v,
          action,
        })
        .catch(() => undefined);
    }
    const s = await ctx.state(ctx.roomId);
    // Only a server-chosen deadline exists: T0 + turnSeconds, whoever's turn it is now.
    expect(s.turnDeadlineAt).toBe(T0 + TURN_MS);
    expect(s.moves.every((m) => !m.timedOut)).toBe(true);
  });
});

describe('setup timer', () => {
  it('60 s to lock in; missing codes are generated by the server at the deadline', async () => {
    const ctx = await lobby();
    await ctx.manager.connect(alice.userId, ctx.roomId);
    await ctx.manager.connect(bob.userId, ctx.roomId);
    await ctx.manager.start(alice.userId, ctx.roomId, aid());
    await ctx.manager.gameAction(alice.userId, {
      roomId: ctx.roomId,
      actionId: aid(),
      clientVersion: 0,
      action: { type: 'SET_SECRET', code: '1234' },
    });
    await vi.advanceTimersByTimeAsync(59_999);
    expect((await ctx.state(ctx.roomId)).phase).toBe('SETUP');
    await vi.advanceTimersByTimeAsync(1);
    const s = await ctx.state(ctx.roomId);
    expect(s.phase).toBe('PLAYING');
    expect(s.players.find((p) => p.id === alice.userId)).toMatchObject({
      secret: '1234',
      autoSecret: false,
    });
    expect(s.players.find((p) => p.id === bob.userId)!.autoSecret).toBe(true);
    // Bob sees his generated code; Alice does not.
    const bobView = duelView((await ctx.manager.getSnapshot(bob.userId, ctx.roomId)).game!.view);
    expect(bobView.mySecretAutoGenerated).toBe(true);
    const aliceView = duelView(
      (await ctx.manager.getSnapshot(alice.userId, ctx.roomId)).game!.view,
    );
    expect(aliceView.opponentSecret).toBeNull();
  });
});

describe('timers and reconnects', () => {
  it('reconnecting during the countdown keeps the same deadline', async () => {
    const ctx = await playing();
    await ctx.manager.disconnect(ctx.first.userId, ctx.roomId);
    await vi.advanceTimersByTimeAsync(20_000);
    const snap = await ctx.manager.connect(ctx.first.userId, ctx.roomId);
    expect(duelView(snap.game!.view).turnDeadlineAt).toBe(T0 + TURN_MS);
    expect(duelView(snap.game!.view).currentTurn).toBe(ctx.first.userId);
    expect(snap.serverTime).toBe(T0 + 20_000);
  });

  it('reconnecting after the turn timed out shows the burned turn and the new countdown', async () => {
    const ctx = await playing();
    await ctx.manager.disconnect(ctx.first.userId, ctx.roomId);
    await vi.advanceTimersByTimeAsync(TURN_MS + 5_000);
    const snap = await ctx.manager.connect(ctx.first.userId, ctx.roomId);
    expect(duelView(snap.game!.view).moves).toEqual([expect.objectContaining({ timedOut: true })]);
    expect(duelView(snap.game!.view).currentTurn).toBe(ctx.second.userId);
    expect(duelView(snap.game!.view).turnDeadlineAt).toBe(T0 + 2 * TURN_MS);
    expect(duelView(snap.game!.view).mySecret).toBe(ctx.first === alice ? '1234' : '5678');
  });

  it('reconnecting one millisecond before the turn deadline: still your turn, 1 ms left', async () => {
    const ctx = await playing();
    await ctx.manager.disconnect(ctx.first.userId, ctx.roomId);
    vi.setSystemTime(T0 + TURN_MS - 1);
    const snap = await ctx.manager.connect(ctx.first.userId, ctx.roomId);
    expect(duelView(snap.game!.view).currentTurn).toBe(ctx.first.userId);
    expect(duelView(snap.game!.view).turnDeadlineAt! - snap.serverTime).toBe(1);
  });

  it('turn deadline and reconnect grace due at the same instant: the game deadline goes first', async () => {
    // 90 s turns: the second player's last-chance turn and their 60 s grace both end at T.
    const ctx = await playing(1, { turnSeconds: 90 });
    await guess(ctx, ctx.first, opponentSecretOf(ctx.first)); // cracked → LAST_CHANCE
    const s = await ctx.state(ctx.roomId);
    expect(s.phase).toBe('LAST_CHANCE');
    const T = s.turnDeadlineAt!;
    vi.setSystemTime(T - GRACE_MS);
    await ctx.manager.disconnect(ctx.second.userId, ctx.roomId);
    await vi.advanceTimersByTimeAsync(GRACE_MS);
    // The timeout ends the game (first player wins by cracking); the grace expiry is moot.
    expect(ctx.finished).toHaveLength(1);
    expect(ctx.finished[0]!.result).toEqual({
      outcome: 'win',
      winnerId: ctx.first.userId,
      reason: 'cracked',
    });
  });

  it('grace expiring before the turn deadline: abandoned, and the turn timer is cleared', async () => {
    const ctx = await playing(1, { turnSeconds: 90 });
    await ctx.manager.disconnect(ctx.first.userId, ctx.roomId);
    await vi.advanceTimersByTimeAsync(GRACE_MS);
    expect(ctx.finished).toHaveLength(1);
    expect(ctx.finished[0]!.result).toMatchObject({
      winnerId: ctx.second.userId,
      reason: 'abandoned',
    });
    await vi.advanceTimersByTimeAsync(90_000);
    expect(ctx.finished).toHaveLength(1);
    expect((await ctx.state(ctx.roomId)).moves).toHaveLength(0);
  });
});
