import { z } from 'zod';
import type { GameEndReason, GameResult } from './games.js';

export const COLOR_CIPHER_ID = 'color-cipher' as const;

/** Color Cipher MVP rules (docs/color-cipher.md). Pattern length and palette are fixed. */
export const CC_LIMITS = {
  patternLength: 4,
  colorCount: 6,
  turnSeconds: { min: 30, max: 90, default: 45 },
  maxGuesses: { min: 8, max: 12, default: 10 },
  setupSeconds: 60,
} as const;

/** The palette, by color id. Each color also has a symbol so it never relies on hue alone. */
export const CC_COLORS = [
  { id: 0, name: 'Ruby', symbol: '●' },
  { id: 1, name: 'Amber', symbol: '▲' },
  { id: 2, name: 'Sun', symbol: '■' },
  { id: 3, name: 'Leaf', symbol: '◆' },
  { id: 4, name: 'Sky', symbol: '★' },
  { id: 5, name: 'Plum', symbol: '✚' },
] as const;

export const ccSettingsSchema = z
  .object({
    patternLength: z.literal(CC_LIMITS.patternLength).default(CC_LIMITS.patternLength),
    colorCount: z.literal(CC_LIMITS.colorCount).default(CC_LIMITS.colorCount),
    turnSeconds: z
      .number()
      .int()
      .min(CC_LIMITS.turnSeconds.min)
      .max(CC_LIMITS.turnSeconds.max)
      .default(CC_LIMITS.turnSeconds.default),
    maxGuesses: z
      .number()
      .int()
      .min(CC_LIMITS.maxGuesses.min)
      .max(CC_LIMITS.maxGuesses.max)
      .default(CC_LIMITS.maxGuesses.default),
  })
  .strict();

export type CcSettings = z.infer<typeof ccSettingsSchema>;

/** Color ids as a digit string ("0312"), bounded; exact length and palette are game rules. */
const patternString = z.string().regex(/^[0-9]{1,8}$/, 'Pattern must be color ids');

export const ccActionSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('SET_SECRET'), pattern: patternString }).strict(),
  z.object({ type: z.literal('GUESS'), pattern: patternString }).strict(),
  z.object({ type: z.literal('FORFEIT') }).strict(),
]);

export type CcPlayerAction = z.infer<typeof ccActionSchema>;

export type CcPhase = 'SETUP' | 'PLAYING' | 'LAST_CHANCE' | 'FINISHED' | 'ABANDONED';

export type CcEndReason = GameEndReason;

export interface CcMove {
  playerId: string;
  /** Color ids, e.g. "0312". Null when the turn timed out. */
  guess: string | null;
  /** Right color, right position. */
  exact: number;
  /** Right color, wrong position. */
  partial: number;
  timedOut: boolean;
  at: number;
  turnNumber: number;
}

export interface CcPlayerPublic {
  userId: string;
  hasSecret: boolean;
  /** Turns used (guesses + timed-out turns). */
  turnsUsed: number;
  guessesLeft: number;
  cracked: boolean;
}

/** What one player is allowed to see. The opponent's pattern only appears once the game is over. */
export interface CcPlayerView {
  gameId: typeof COLOR_CIPHER_ID;
  phase: CcPhase;
  version: number;
  settings: CcSettings;
  me: string;
  mySecret: string | null;
  mySecretAutoGenerated: boolean;
  opponentSecret: string | null;
  players: CcPlayerPublic[];
  firstPlayerId: string;
  currentTurn: string | null;
  setupDeadlineAt: number | null;
  turnStartedAt: number | null;
  turnDeadlineAt: number | null;
  /** Every guess in order, both players; each scored against the *other* player's pattern. */
  moves: CcMove[];
  result: GameResult | null;
}

/** Spectator/analytics view: never includes any pattern. */
export type CcPublicView = Omit<
  CcPlayerView,
  'me' | 'mySecret' | 'mySecretAutoGenerated' | 'opponentSecret'
>;

/** Rule check shared by client (instant feedback) and server (authoritative). */
export function checkPattern(
  pattern: string,
  length: number = CC_LIMITS.patternLength,
  colorCount: number = CC_LIMITS.colorCount,
): 'ok' | 'length' | 'color' {
  if (pattern.length !== length) return 'length';
  for (const ch of pattern) {
    const id = ch.charCodeAt(0) - 48;
    if (id < 0 || id >= colorCount) return 'color';
  }
  return 'ok';
}
