import { z } from 'zod';
import type { GameEndReason, GameResult } from './games.js';

export const CRACK_THE_CODE_ID = 'crack-the-code' as const;

/** Configurable ranges and defaults for Crack the Code (approved MVP rules). */
export const CTC_LIMITS = {
  codeLength: { min: 3, max: 5, default: 4 },
  turnSeconds: { min: 30, max: 90, default: 45 },
  maxGuesses: { min: 8, max: 12, default: 10 },
  setupSeconds: 60,
} as const;

export const ctcSettingsSchema = z
  .object({
    codeLength: z
      .number()
      .int()
      .min(CTC_LIMITS.codeLength.min)
      .max(CTC_LIMITS.codeLength.max)
      .default(CTC_LIMITS.codeLength.default),
    turnSeconds: z
      .number()
      .int()
      .min(CTC_LIMITS.turnSeconds.min)
      .max(CTC_LIMITS.turnSeconds.max)
      .default(CTC_LIMITS.turnSeconds.default),
    maxGuesses: z
      .number()
      .int()
      .min(CTC_LIMITS.maxGuesses.min)
      .max(CTC_LIMITS.maxGuesses.max)
      .default(CTC_LIMITS.maxGuesses.default),
  })
  .strict();

export type CtcSettings = z.infer<typeof ctcSettingsSchema>;

export const DEFAULT_CTC_SETTINGS: CtcSettings = {
  codeLength: CTC_LIMITS.codeLength.default,
  turnSeconds: CTC_LIMITS.turnSeconds.default,
  maxGuesses: CTC_LIMITS.maxGuesses.default,
};

/** Digits only, bounded length; uniqueness and exact length are game rules checked by the server. */
const codeString = z.string().regex(/^[0-9]{3,5}$/, 'Code must be 3–5 digits');

export const ctcActionSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('SET_SECRET'), code: codeString }).strict(),
  z.object({ type: z.literal('GUESS'), guess: codeString }).strict(),
  z.object({ type: z.literal('FORFEIT') }).strict(),
]);

export type CtcPlayerAction = z.infer<typeof ctcActionSchema>;

export type CtcPhase = 'SETUP' | 'PLAYING' | 'LAST_CHANCE' | 'FINISHED' | 'ABANDONED';

/** Crack the Code uses the shared end reasons unchanged. */
export type CtcEndReason = GameEndReason;

export interface CtcMove {
  playerId: string;
  /** Null when the turn timed out. */
  guess: string | null;
  bulls: number;
  cows: number;
  timedOut: boolean;
  at: number;
  turnNumber: number;
}

export interface CtcPlayerPublic {
  userId: string;
  hasSecret: boolean;
  /** Turns used (guesses + timed-out turns). */
  turnsUsed: number;
  guessesLeft: number;
  cracked: boolean;
}

/** What one player is allowed to see. Opponent secret only appears once the game is over. */
export interface CtcPlayerView {
  gameId: typeof CRACK_THE_CODE_ID;
  phase: CtcPhase;
  version: number;
  settings: CtcSettings;
  me: string;
  mySecret: string | null;
  mySecretAutoGenerated: boolean;
  opponentSecret: string | null;
  players: CtcPlayerPublic[];
  firstPlayerId: string;
  currentTurn: string | null;
  setupDeadlineAt: number | null;
  turnStartedAt: number | null;
  turnDeadlineAt: number | null;
  /** Every move in order, both players. Each move is scored against the *other* player's code. */
  moves: CtcMove[];
  result: GameResult | null;
}

/** Spectator/analytics view: never includes any secret. */
export type CtcPublicView = Omit<
  CtcPlayerView,
  'me' | 'mySecret' | 'mySecretAutoGenerated' | 'opponentSecret'
>;

/** Rule check shared by client (instant feedback) and server (authoritative). */
export function checkCode(code: string, length: number): 'ok' | 'length' | 'digits' | 'repeat' {
  if (code.length !== length) return 'length';
  if (!/^[0-9]+$/.test(code)) return 'digits';
  if (new Set(code).size !== code.length) return 'repeat';
  return 'ok';
}
